# -*- coding: utf-8 -*-
"""data science and machine leraning project based on real world

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13MNckPNmB76-nHhAajDGEf7qTUOUL6u4
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
df=pd.read_csv("Default_Fin.csv")
df.head()
df.info()
df.isnull().sum()
df.fillna(0,inplace=True)
df.drop_duplicates(inplace=True)
sns.countplot(x='Defaulted?',data=df)
plt.title('Loan Default count')
plt.show()
sns.histplot(x='Annual Salary', data=df)
plt.title('Income Distribution')
plt.show()

# Define features (X) and target (y)
X = df.drop(['Index', 'Defaulted?'], axis=1)
y = df['Defaulted?']

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

model=LogisticRegression()
model.fit(X_train,y_train)
y_pred=model.predict(X_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

print(df.columns)